package org.litesoft.events.api.v03.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.validation.annotation.Validated;

/**
 * AbstractAllEventProperties
 */
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-02-11T00:44:24.775Z[GMT]")
public abstract class AbstractAllEventProperties<T extends AbstractAllEventProperties<T>> extends AbstractCommonEventProperties<T> {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("updateToken")
  private String updateToken = null;

  public T id(String id) {
    this.id = id;
    return us();
  }

  /**
   * Unique - system assigned.
   *
   * @return id
   **/
  @ApiModelProperty(example = "d290f1ee-6c54-4b01-90e6-d701748f0851", value = "Unique - system assigned.")

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }
  
  
  public T updateToken(String updateToken) {
    this.updateToken = updateToken;
    return us();
  }

  /**
   * Opaque - generated by the system to support Optomistic locking.
   *
   * @return updateToken
   **/
  @ApiModelProperty(example = "d290f1ee-6c54-4b01-90e6-d701748f0851", value = "Opaque - generated by the system to support Optomistic locking.")

  public String getUpdateToken() {
    return updateToken;
  }

  public void setUpdateToken(String updateToken) {
    this.updateToken = updateToken;
  }
}
