server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    maxActive: 4
    allowMultiQueries: true
    username: root
    password: